name: Build iOS App for Simulator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-2/files-2.1
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build shared KMM module
        run: ./gradlew :shared:build

      - name: Build iOS App for Simulator (Appetize)
        run: |
          xcodebuild clean build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CONFIGURATION_BUILD_DIR=build/simulator

      - name: Zip .app
        run: |
          cd build/simulator
          zip -r iosApp-simulator.zip iosApp.app

      - name: Upload simulator .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iosApp-simulator
          path: build/simulator/iosApp-simulator.zip
