name: Build iOS App for Simulator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Zip .app
        run: |
          cd iosApp/build/simulator
          zip -r iosApp-simulator.zip iosApp.app

      - name: Upload simulator .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iosApp-simulator
          path: iosApp/build/simulator/iosApp-simulator.zip

