name: Build iOS App for Simulator (Appetize)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build shared KMM module
        run: ./gradlew :shared:build

      - name: Build iOS App for Simulator (Appetize)
        run: |
          xcodebuild clean build \
            -project iosApp/iosApp.xcodeproj \ 
            -scheme iosApp \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CONFIGURATION_BUILD_DIR=build/simulator


      - name: Package .app into zip
        run: |
          cd build/simulator
          zip -r iosApp-simulator.zip iosApp.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iosApp-simulator
          path: build/simulator/iosApp-simulator.zip
