name: Build iOS App (KMM no CocoaPods)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-2/files-2.1
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17 (Kotlin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build shared KMM module
        run: ./gradlew :shared:build

      - name: Debug Xcode schemes
        run: xcodebuild -list -project iosApp/iosApp.xcodeproj

      - name: Build iOS app with xcodebuild
        run: |
          xcodebuild clean build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM=5Y5H7652QW

      - name: Find and archive .app bundle
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" | grep Debug-iphoneos | head -n 1)
          echo "App found at: $APP_PATH"
          zip -r iosApp.zip "$APP_PATH"
        shell: bash

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: iosApp
          path: iosApp.zip
