name: Build iOS App (KMM no CocoaPods)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-2/files-2.1
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17 (Kotlin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build shared KMM module
        run: ./gradlew :shared:build

      - name: Build iOS app for Simulator
        run: |
          xcodebuild clean build \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGNING_ALLOWED=NO

      - name: Find .app for simulator
        run: |
          mkdir -p build/simulator
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" | grep "Debug-iphonesimulator" | head -n 1)
          echo "Found app at $APP_PATH"
          cp -R "$APP_PATH" build/simulator/

      - name: Zip .app for Appetize
        run: |
          cd build/simulator
          zip -r iosApp-simulator.zip *.app

      - name: Upload iOS simulator .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iosApp-simulator
          path: build/simulator/iosApp-simulator.zip
